version: '3'
services:
  simple_whisper_web:
    image: arnecuperus/simple_whisper_webapp:v1.0.4
    container_name: simple_whisper_web
    ports:
      - "9999:9999"
    environment:
      - GUNICORN_THREADS=2
      - USE_GPU=false
      - FLASK_DEBUG=false
      - MODEL_SIZE=large-v2
    volumes:
      - ./data:/data
    restart: unless-stopped